### PR TITLE
roast spec: Add environment

### PR DESCRIPTION
**Pull request by airencracken**
Sometimes the roasting environment can have interplay with the
roast so tracking variations with things like ambient temperature,
humidity, and barometric pressure can be handy.

### CODE REVIEW

**Comment by airencracken** [comment]
Now that I think of it, I ought to have specified that the measurements of temp/humidity/pressure ought to be in floats.

**Comment by ryands** [comment]
+1 for using a float for temp/humidity/pressure.

Should we use metric units? Or should we allow units to be specified?

**Comment by airencracken** [comment]
Global config option with methods to convert? That way roast sizes and ambient figures are all consistent.

**Comment by airencracken** [comment]
I suppose I could squash all those fucks into a branch or something, but I kinda don't care.

**Pull request merged**
